version: 2
updates:
  - package-ecosystem: docker
    directory: "/tools/debugging"
    schedule:
      interval: daily
  - package-ecosystem: gomod
    directory: "/"
    schedule:
      interval: daily
